DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Teacher;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS Classroom;
DROP TABLE IF EXISTS TeachAssign;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Schedule;
DROP TABLE IF EXISTS StudentClass;